### ISSUE TITLE
Check why @mui/base is needed

### ISSUE THREAD

**Issue by spaenleh** [graasp/graasp-app-cv-tools#11]
Why do you need this ?

_Originally posted by @spaenleh in https://github.com/graasp/graasp-app-cv-tools/pull/3#discussion_r1217761799_

**Comment by AmeerTawfik** [comment]
I have installed it the time I was trying to apply an approach for the datepicker range component, and it doesn't necessary, but if i removed it, some errors will appear, an example for that is:
```
ERROR in ./node_modules/@mui/private-theming/node_modules/@mui/utils/esm/index.js

Module build failed (from ./node_modules/source-map-loader/dist/cjs.js):
Error: ENOENT: no such file or directory, open '/Users/ameer/graasp-app-cv-tools/node_modules/@mui/private-theming/node_modules/@mui/utils/esm/index.js'
```

**Comment by spaenleh** [comment]
It looks like updating the other MUI packages and removing `@mui/base` works. Your error might have been because the version of `@mui/base` pulled by the other mui packages was too old.
